import product1 from "../../../../../../../assets/images/homepage/product1.png";
import product4 from "../../../../../../../assets/images/homepage/product4.png";
import product5 from "../../../../../../../assets/images/homepage/product5.png";
import product6 from "../../../../../../../assets/images/homepage/product6.png";

const SingleCardData = [
  {
    id: "qaz",
    bg: "#EFEFEF",
    image: product1,
    featured: true,
    bestseller: true,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 3,
    personsRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "wsx",
    bg: "#FBF2F2",
    image: product4,
    featured: true,
    bestseller: false,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "edc",
    bg: "#EDF1F0",
    image: product5,
    featured: true,
    bestseller: true,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "rfv",
    bg: "#F9F5E7",
    image: product6,
    featured: true,
    bestseller: true,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "tgb",
    bg: "#EFEFEF",
    image: product1,
    featured: true,
    bestseller: false,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "yhn",
    bg: "#FBF2F2",
    image: product4,
    featured: true,
    bestseller: false,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "ujm",
    bg: "#EDF1F0",
    image: product5,
    featured: true,
    bestseller: true,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "iko",
    bg: "#F9F5E7",
    image: product6,
    featured: true,
    bestseller: false,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 5,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
  {
    id: "lps",
    bg: "#EFEFEF",
    image: product1,
    featured: true,
    bestseller: false,
    category: "Acne-prone & Oily Skin",
    qty: "50 ml",
    productName: "Pure Vitamin C Serum",
    rating: 1,
    personRated: "(583)",
    price: "$12.00 - $20.00",
  },
];

export default SingleCardData;
