export const filterOptions = [
    {
        id: "tags",
        type: "tags",
        filterName: "Product Tags",
        showName: true,
        options: ["Anti-Ageing", "Skincare Treatments", "Oils & Serums", "Moisturisers", "Cleansers"],
    },
    {
        id: "saleCheckbox",
        type: "checkbox",
        filterName: "On Sale/In Stock",
        showName: false,
        options: ["On Sale", "In Stock"],
    },
    {
        id: "priceRange",
        type: "range",
        filterName: "Price",
        showName: true,
        options: [""],
    },
    {
        id: "sizeAcc",
        type: "accordian",
        filterName: "Size",
        showName: true,
        options: ["100 ml", "150 ml", "200 ml"],
    },
    {
        id: "preferenceAcc",
        type: "accordian",
        filterName: "Preference",
        showName: true,
        options: ["Natural 450", "Vitamin C 89", "Clinically Proven 48", "Paraffin-Free 4", "Gluten Free 23", "Hyaluronic Acid 27", "Vitamin D 90", ],
    },
    {
        id: "genderAcc",
        type: "accordian",
        filterName: "Gender",
        showName: true,
        options: ["Male", "Female"],
    },
    {
        id: "discountAcc",
        type: "accordian",
        filterName: "Discount",
        showName: true,
        options: ["20%", "49%"],
    },
    {
        id: "skinAcc",
        type: "accordian",
        filterName: "Skin Type",
        showName: true,
        options: ["Smooth", "Rough", "Patched"],
    },
    {
        id: "concernAcc",
        type: "accordian",
        filterName: "Concern",
        showName: true,
        options: ["Gluten Free", "Xyloc Free"],
    },
];